### ISSUE TITLE
[Feature] Support bounded time slice in timeline query

### ISSUE THREAD

**Issue by shawncao** [varchar-io/nebula#180]
(Context, this is how the current timeline works)
The timeline query will have 3 basic inputs: start time, end time, and window size, simply it just slices the whole time range into pieces according to the window size.

For general timeline, this works great as long as the window size is flexible, but there are real business scenarios that they want the timeline to fit into the boundaries of a given unit, such as Weekly, Monthly, Quarterly, or Yearly.

In these cases, data needs to fit into the boundary of the time unit, and should not cross multiple different units.

The change should be simple in the query building/planning phase, but need to introduce a new interface and enough tests.

(Suggestion: A good starting task for new committer.)

**Comment by caoash** [comment]
(Closed?) by https://github.com/varchar-io/nebula/pull/182

**Comment by shawncao** [comment]
happily to close it, @caoash 
Just a tip - next time, you can associate the Issue with your PR, so that it will automatically close the issue when the PR is completed.

**Comment by caoash** [comment]
Got it, thanks
