### ISSUE TITLE
[Ingestion] Hourly Roll spec support

### ISSUE THREAD

**Issue by chenqin** [varchar-io/nebula#33]
The goal here is to support reading from hourly partitioned s3 directory.

https://ci.apache.org/projects/flink/flink-docs-release-1.11/dev/table/connectors/filesystem.html#full-example

1. we need to improve genSpecs4Roll and add hourly partitioned specs instead of daily. Currently macro is hard coded as date (daily), hence some work to read macro and decided how genSpecs4Roll doing listing respectively

2. often there are commit flag _SUCCESS when an hourly partition finished. fs->list() should be able to customize it's behavior and let user decide if they want fresh yet incomplete dateset or complete yet a bit long latency dateset.

detail discussion on https://github.com/varchar-io/nebula/pull/34

**Comment by shawncao** [comment]
Thanks @chenqin ! I just reviewed the PR. 
Yes - currently we only have one hard-coded macro, it would be great to refactor this part to 
- Internally define some supported macros.
- Detect macro set in use from given path pattern.
- Compute correct time column value if it's used by time column.

But it's just good to have, we can address the problem separately.
