### ISSUE TITLE
Update file header

### ISSUE THREAD

**Issue by shawncao** [varchar-io/nebula#85]
Replace all occurrences of below 

`Copyright 2017-present Shawn Cao` from file header into `Copyright 2017-present varchar.io`

**Comment by Jwright707** [comment]
Hi @shawncao I would like to tackle this issue 😀

**Comment by shawncao** [comment]
Sure, you're very welcomed! Feel free to assign it to yourself! Thanks for offering the help!

**Comment by Jwright707** [comment]
Awesome, thank you @shawncao . Just made a PR for this 👍

**Comment by shawncao** [comment]
Great, thanks for your help @Jwright707, love to merge it, feel free to navigate other issues too :), 👍
